/*
 * Argon2id — passphrase hashing and key derivation.
 *
 * Two distinct outputs live here and they must not be confused:
 *
 *   hashPassphrase / verifyPassphrase
 *       produce and consume a self-contained PHC string
 *       (`$argon2id$v=19$m=262144,t=3,p=4$<salt>$<digest>`). Equality checking only —
 *       no usable key falls out of it. This is what you store if all you need to know
 *       later is "was that the same passphrase".
 *
 *   deriveKey
 *       returns RAW key bytes for use as an AES-256-GCM key. Nothing about the
 *       derivation is stored alongside it; the caller records the salt and the
 *       parameters (the vault does this per key slot) and must reproduce them exactly.
 *
 * Everything is async. @node-rs/argon2's promise API runs the hash on a worker thread,
 * off the Electron main thread — a 400 ms synchronous derivation would freeze every
 * window in the app, and unlocking is precisely the moment the user is watching.
 *
 * ---------------------------------------------------------------------------
 *  PARAMETER CHOICE — desktop app, 2026
 * ---------------------------------------------------------------------------
 *
 * Argon2id is memory-hard: an attacker's cost per guess scales with `memoryCost`,
 * because memory (not arithmetic) is what a GPU or ASIC cannot cheaply multiply. Time
 * cost and parallelism buy far less per unit of user-visible delay. So the rule is:
 * spend the budget on memory first, then on iterations.
 *
 * Reference points:
 *   OWASP 2025 floor          m = 19 MiB,  t = 2, p = 1
 *   RFC 9106 §4 first option  m = 2 GiB,   t = 1, p = 4   (server-class, back-end use)
 *   RFC 9106 §4 second option m = 64 MiB,  t = 3, p = 4   (memory-constrained)
 *
 * PASSPHRASE_KDF — m = 256 MiB, t = 3, p = 4
 *
 *   The passphrase is human-chosen and therefore the weakest secret in the system;
 *   it is the one that has to be expensive to guess. A vault unlock happens once when
 *   a company is opened, not once per request, so the latency budget is a whole human
 *   moment rather than a few milliseconds. That is a fundamentally different tradeoff
 *   from a web login, and it is why these numbers sit well above the OWASP floor.
 *
 *   256 MiB is 13x the OWASP floor and 4x RFC 9106's memory-constrained option. It is
 *   a transient allocation, freed the moment the derivation returns, so it is safe on
 *   a 4 GB machine. The ceiling is set by that low-end machine, not by a dev laptop:
 *   RFC 9106's 2 GiB option would make Coffer unopenable on the hardware a small
 *   business actually runs, and an ERP that cannot open its books is a worse failure
 *   than a slightly cheaper guess.
 *
 *   t = 3 and p = 4 follow RFC 9106's second option unchanged. p = 4 uses the cores a
 *   desktop already has, which lowers wall-clock time without lowering attacker cost —
 *   note that p is part of the hash, so it can never be tuned per machine.
 *
 *   Measured: ~120 ms on a 16-core desktop, and roughly 0.4-0.8 s on a low-end 2- to
 *   4-core laptop. That is the intended feel: noticeable, not annoying.
 *
 * RECOVERY_KDF — m = 64 MiB, t = 3, p = 4  (RFC 9106's second option, unmodified)
 *
 *   A recovery code is 100 bits of uniform randomness generated by us (see
 *   recovery-codes.ts), not something a human invented. Brute force is already
 *   arithmetically hopeless, so memory-hardness here is defence in depth against our
 *   own future mistakes rather than the thing holding the door shut. The lighter
 *   profile matters because a recovery attempt must try each unspent slot in turn:
 *   five derivations at ~30 ms is a fast recovery, five at ~120 ms is a slow one, and
 *   neither changes what an attacker has to do.
 *
 * Both profiles are recorded per key slot in the vault file, never assumed. Raising
 * them later therefore does not lock anyone out of an existing vault — see
 * needsKdfUpgrade in vault.ts.
 */

import { timingSafeEqual } from 'node:crypto'
import { hash, hashRaw, verify } from '@node-rs/argon2'
import type { Algorithm } from '@node-rs/argon2'

import { SecurityError } from './errors'

/*
 * `Algorithm` is an ambient const enum. `isolatedModules` forbids reading its members
 * across a module boundary, so the numeric value is used with a type assertion back to
 * the enum. Argon2id === 2; the type import keeps that assertion honest.
 */
const ARGON2ID = 2 as Algorithm

/** Bytes of raw key material a derivation produces by default. AES-256 wants 32. */
export const KDF_OUTPUT_BYTES = 32

/** Bytes of salt. 16 is the Argon2 recommendation and the PHC default. */
export const SALT_BYTES = 16

/** Argon2 refuses salts shorter than 8 bytes; so do we, one layer earlier. */
export const MIN_SALT_BYTES = 8

/*
 * Accepted parameter range. The floor rejects parameters too weak to be worth calling
 * a KDF. The ceiling exists because KDF parameters are read from a file: without it, a
 * vault edited to say `memoryCost: 68719476736` would have Coffer try to allocate 64 TiB
 * on the unlock path. A tampered file must fail, not take the process down with it.
 */
export const MIN_MEMORY_COST = 8 * 1024 // 8 MiB, in KiB
export const MAX_MEMORY_COST = 2 * 1024 * 1024 // 2 GiB, in KiB
export const MIN_TIME_COST = 1
export const MAX_TIME_COST = 64
export const MIN_PARALLELISM = 1
export const MAX_PARALLELISM = 16

/** Argon2 parameters. `memoryCost` is in KiB, matching the Argon2 convention. */
export interface Argon2Params {
  readonly algorithm: 'argon2id'
  /** Memory in KiB. */
  readonly memoryCost: number
  /** Iterations (passes over memory). */
  readonly timeCost: number
  /** Lanes. Part of the hash — the same value must be used to reproduce a key. */
  readonly parallelism: number
}

/** For the user's passphrase: the weakest secret, so the most expensive to guess. */
export const PASSPHRASE_KDF: Argon2Params = {
  algorithm: 'argon2id',
  memoryCost: 256 * 1024,
  timeCost: 3,
  parallelism: 4,
}

/** For 100-bit random recovery codes, which do not need the passphrase profile. */
export const RECOVERY_KDF: Argon2Params = {
  algorithm: 'argon2id',
  memoryCost: 64 * 1024,
  timeCost: 3,
  parallelism: 4,
}

/**
 * Reject parameters that are unusable or dangerous before handing them to Argon2.
 *
 * @throws SecurityError `KDF_PARAMS_INVALID`
 */
export function assertValidKdfParams(params: Argon2Params): void {
  const isValid =
    params.algorithm === 'argon2id' &&
    Number.isInteger(params.memoryCost) &&
    params.memoryCost >= MIN_MEMORY_COST &&
    params.memoryCost <= MAX_MEMORY_COST &&
    Number.isInteger(params.timeCost) &&
    params.timeCost >= MIN_TIME_COST &&
    params.timeCost <= MAX_TIME_COST &&
    Number.isInteger(params.parallelism) &&
    params.parallelism >= MIN_PARALLELISM &&
    params.parallelism <= MAX_PARALLELISM
  if (!isValid) {
    throw new SecurityError(
      'KDF_PARAMS_INVALID',
      'The key derivation parameters are outside the range this version accepts.',
    )
  }
}

/**
 * Derive raw key material from a secret and a salt.
 *
 * The output is a key, not a hash to be stored: keep it in memory only, and zero it
 * when you are done (see `zeroize` in dek.ts).
 *
 * @param secret Passphrase bytes, recovery-code bytes, or any other input keying material.
 * @param salt At least 8 bytes, 16 recommended. Unique per slot, stored in the clear.
 * @throws SecurityError `KDF_PARAMS_INVALID` | `KEY_MATERIAL_INVALID`
 */
export async function deriveKey(
  secret: Buffer,
  salt: Buffer,
  params: Argon2Params,
  outputLen: number = KDF_OUTPUT_BYTES,
): Promise<Buffer> {
  assertValidKdfParams(params)
  if (salt.length < MIN_SALT_BYTES) {
    throw new SecurityError('KEY_MATERIAL_INVALID', 'The key derivation salt is too short.')
  }
  if (!Number.isInteger(outputLen) || outputLen < 16 || outputLen > 1024) {
    throw new SecurityError('KEY_MATERIAL_INVALID', 'The requested key length is not supported.')
  }
  if (secret.length === 0) {
    throw new SecurityError('KEY_MATERIAL_INVALID', 'The key derivation input was empty.')
  }
  const raw = await hashRaw(secret, {
    algorithm: ARGON2ID,
    salt,
    memoryCost: params.memoryCost,
    timeCost: params.timeCost,
    parallelism: params.parallelism,
    outputLen,
  })
  return Buffer.from(raw)
}

/**
 * Hash a passphrase into a self-contained PHC string, salt and parameters included.
 *
 * Two calls with the same passphrase return different strings — the salt is random per
 * hash. Compare with `verifyPassphrase`, never with `===`.
 *
 * @throws SecurityError `PASSPHRASE_EMPTY`
 */
export async function hashPassphrase(passphrase: string): Promise<string> {
  assertPassphraseNotEmpty(passphrase)
  return hash(passphrase, {
    algorithm: ARGON2ID,
    memoryCost: PASSPHRASE_KDF.memoryCost,
    timeCost: PASSPHRASE_KDF.timeCost,
    parallelism: PASSPHRASE_KDF.parallelism,
    outputLen: KDF_OUTPUT_BYTES,
  })
}

/**
 * Verify a passphrase against a stored PHC string.
 *
 * The comparison is constant-time with respect to the digest: Argon2 recomputes the
 * hash using the parameters embedded in `storedHash` and compares the result under
 * `timingSafeEqual`, so a near-miss and a wild miss take the same time. Returns
 * `false` for a wrong passphrase rather than throwing, because a wrong passphrase is
 * an expected outcome and not an exceptional one.
 *
 * @throws SecurityError `PASSPHRASE_HASH_MALFORMED` if the stored hash cannot be read.
 */
export async function verifyPassphrase(storedHash: string, passphrase: string): Promise<boolean> {
  if (typeof storedHash !== 'string' || storedHash.length === 0) {
    throw new SecurityError(
      'PASSPHRASE_HASH_MALFORMED',
      'The stored passphrase hash is missing or unreadable.',
    )
  }
  try {
    return await verify(storedHash, passphrase)
  } catch {
    throw new SecurityError(
      'PASSPHRASE_HASH_MALFORMED',
      'The stored passphrase hash is missing or unreadable.',
    )
  }
}

/**
 * Constant-time equality for secrets and digests.
 *
 * Length is compared first and leaks — `timingSafeEqual` throws on a length mismatch,
 * and the lengths involved here (32-byte verifiers, 16-byte tags) are fixed and public
 * anyway. The contents never leak.
 */
export function constantTimeEqual(a: Buffer, b: Buffer): boolean {
  if (a.length !== b.length) {
    return false
  }
  return timingSafeEqual(a, b)
}

/**
 * True when `storedHash` was produced with parameters weaker than the current profile,
 * or cannot be read at all. The caller re-hashes on the next successful verification.
 */
export function needsRehash(storedHash: string): boolean {
  const parsed = parsePhcParams(storedHash)
  if (parsed === null) {
    return true
  }
  return (
    parsed.algorithm !== 'argon2id' ||
    parsed.version < 19 ||
    parsed.memoryCost < PASSPHRASE_KDF.memoryCost ||
    parsed.timeCost < PASSPHRASE_KDF.timeCost ||
    parsed.parallelism < PASSPHRASE_KDF.parallelism
  )
}

export interface PhcParams {
  algorithm: string
  version: number
  memoryCost: number
  timeCost: number
  parallelism: number
}

/**
 * Read the header of a PHC string: `$argon2id$v=19$m=262144,t=3,p=4$<salt>$<digest>`.
 * Returns null rather than throwing — every caller here treats unreadable as "replace it".
 */
export function parsePhcParams(storedHash: string): PhcParams | null {
  if (typeof storedHash !== 'string') {
    return null
  }
  const parts = storedHash.split('$')
  // ['', 'argon2id', 'v=19', 'm=262144,t=3,p=4', '<salt>', '<digest>']
  if (parts.length < 6) {
    return null
  }
  const algorithm = parts[1]
  const versionField = parts[2]
  const paramField = parts[3]
  if (
    algorithm === undefined ||
    versionField === undefined ||
    paramField === undefined ||
    !versionField.startsWith('v=')
  ) {
    return null
  }
  const version = Number(versionField.slice(2))
  const values = new Map<string, number>()
  for (const pair of paramField.split(',')) {
    const [key, value] = pair.split('=')
    if (key !== undefined && value !== undefined) {
      values.set(key, Number(value))
    }
  }
  const memoryCost = values.get('m')
  const timeCost = values.get('t')
  const parallelism = values.get('p')
  if (
    !Number.isFinite(version) ||
    memoryCost === undefined ||
    timeCost === undefined ||
    parallelism === undefined ||
    !Number.isFinite(memoryCost) ||
    !Number.isFinite(timeCost) ||
    !Number.isFinite(parallelism)
  ) {
    return null
  }
  return { algorithm, version, memoryCost, timeCost, parallelism }
}

/**
 * A passphrase must contain something. Strength policy belongs to the layer that can
 * talk to the user about it — this is only the invariant that makes the crypto sound.
 *
 * @throws SecurityError `PASSPHRASE_EMPTY`
 */
export function assertPassphraseNotEmpty(passphrase: string): void {
  if (typeof passphrase !== 'string' || passphrase.trim().length === 0) {
    throw new SecurityError('PASSPHRASE_EMPTY', 'Enter a passphrase.')
  }
}
